@startuml

title __PINSETTER's Class Diagram__\n

  namespace  {
    namespace insetter {
      class pinsetter.PinSetterView {
          - firstRoll : JPanel
          - frame : JFrame
          - pinVect : Vector
          - secondRoll : JPanel
          + PinSetterView()
          + hide()
          {static} + main()
          + receivePinsetterEvent()
          + show()
      }
    }
  }
  

  namespace  {
    namespace insetter {
      class pinsetter.PinSetterView {
          - firstRoll : JPanel
          - frame : JFrame
          - pinVect : Vector
          - secondRoll : JPanel
          + PinSetterView()
          + hide()
          {static} + main()
          + receivePinsetterEvent()
          + show()
      }
    }
  }
  

  namespace  {
    namespace insetter {
      class pinsetter.Pinsetter {
          - foul : boolean
          - pins : boolean[]
          - rnd : Random
          - subscribers : Vector
          - throwNumber : int
          + Pinsetter()
          + ballThrown()
          + reset()
          + resetPins()
          + subscribe()
          - sendEvent()
      }
    }
  }
  

  namespace  {
    namespace insetter {
      class pinsetter.Pinsetter {
          - foul : boolean
          - pins : boolean[]
          - rnd : Random
          - subscribers : Vector
          - throwNumber : int
          + Pinsetter()
          + ballThrown()
          + reset()
          + resetPins()
          + subscribe()
          - sendEvent()
      }
    }
  }
  

  namespace  {
    namespace insetter {
      interface pinsetter.PinsetterObserver {
          {abstract} + receivePinsetterEvent()
      }
    }
  }
  

  namespace  {
    namespace insetter {
      interface pinsetter.PinsetterObserver {
          {abstract} + receivePinsetterEvent()
      }
    }
  }
  

  pinsetter.PinSetterView .up.|> pinsetter.PinsetterObserver
  pinsetter.PinSetterView .up.|> PinsetterObserver


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
