@startuml

title __SCORE's Class Diagram__\n

  namespace  {
    namespace core {
      class score.PrintableText {
          ~ POINTS_PER_INCH : int
          ~ text : String
          + PrintableText()
          + print()
      }
    }
  }
  

  namespace  {
    namespace core {
      class score.PrintableText {
          ~ POINTS_PER_INCH : int
          ~ text : String
          + PrintableText()
          + print()
      }
    }
  }
  

  namespace  {
    namespace core {
      class score.Score {
          - date : String
          - nick : String
          - score : String
          + Score()
          + getDate()
          + getNickName()
          + getScore()
          + toString()
      }
    }
  }
  

  namespace  {
    namespace core {
      class score.Score {
          - date : String
          - nick : String
          - score : String
          + Score()
          + getDate()
          + getNickName()
          + getScore()
          + toString()
      }
    }
  }
  

  namespace  {
    namespace core {
      class score.ScoreHistoryFile {
          {static} - SCOREHISTORY_DAT : String
          + ScoreHistoryFile()
          {static} + addScore()
          {static} + getScores()
      }
    }
  }
  

  namespace  {
    namespace core {
      class score.ScoreHistoryFile {
          {static} - SCOREHISTORY_DAT : String
          {static} + addScore()
          {static} + getScores()
      }
    }
  }
  

  namespace  {
    namespace core {
      class score.ScoreReport {
          - content : String
          + ScoreReport()
          + sendEmail()
          + sendPrintout()
          + sendln()
          + sendln()
      }
    }
  }
  

  namespace  {
    namespace core {
      class score.ScoreReport {
          - content : String
          + ScoreReport()
          + sendEmail()
          + sendPrintout()
          + sendln()
          + sendln()
      }
    }
  }
  

  score.PrintableText .up.|> java.awt.print.Printable
  score.PrintableText .up.|> Printable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
